version: "3.8"
services:
  frontend:
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    expose:
      - 8000
    volumes:
      - ./frontend/:/var/www/html/app
    tty: true
    command: >
      -c "yarn && yarn dev"
    ports:
      - "8000:8000"
  db:
    image: surrealdb/surrealdb:latest
    ports:
      - "5432:5432"
    command: "start --log trace --bind 0.0.0.0:5432 --user root --pass root file://data/"
    volumes:
      - ./data:/data
volumes:
  data: